comment out database

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - main
+      - test_ci
   pull_request:
     branches:
       - main
@@ -11,20 +12,21 @@ on:
 jobs:
   backend:
     runs-on: ubuntu-latest
-    services:
-      postgres:
-        image: postgres:14
-        ports:
-          - 5432:5432
-        env:
-          POSTGRES_USER: ${{ secrets.PGUSER }}
-          POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD }}
-          POSTGRES_DB: backend_test
-        options: >-
-          --health-cmd="pg_isready -U postgres"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=5
+
+    # services:
+      # postgres:
+      #   image: postgres:14
+      #   ports:
+      #     - 5432:5432
+      #   env:
+      #     POSTGRES_USER: ${{ secrets.PGUSER }}
+      #     POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD }}
+      #     POSTGRES_DB: backend_test
+      #   options: >-
+      #     --health-cmd="pg_isready -U postgres"
+      #     --health-interval=10s
+      #     --health-timeout=5s
+      #     --health-retries=5
 
     steps:
       - name: Checkout code
@@ -33,27 +35,33 @@ jobs:
       - name: Set up Ruby
         uses: ruby/setup-ruby@v1
         with:
-          ruby-version: 3.2.2  
+          ruby-version: 3.2.2
 
       - name: Install backend dependencies
         run: |
           cd backend
           bundle install
 
-      - name: Wait for PostgreSQL to be ready
-        run: |
-          while ! pg_isready -h postgres -U postgres; do
-            echo "Waiting for PostgreSQL to be ready..."
-            sleep 1
-          done
+      - name: Set up Docker Compose
+        uses: docker/setup-buildx-action@v2
+        with:
+          version: latest
 
-      - name: Set up database
+      - name: Build and run containers
         run: |
-          cd backend
-          bundle exec rake db:create
-          bundle exec rake db:schema:load
+          docker-compose -f docker-compose.yml up -d
+
+      # - name: Wait for PostgreSQL to be ready
+      #   run: |
+      #     while ! docker exec backend pg_isready -h postgres -U postgres; do
+      #       echo "Waiting for PostgreSQL to be ready..."
+      #       sleep 1
+      #     done
+
+      # - name: Run database setup
+      #   run: |
+      #     docker-compose exec backend rake db:create db:migrate
 
       - name: Run backend tests
         run: |
-          cd backend
-          bundle exec rspec
+          docker-compose exec backend bundle exec rspec
